### ISSUE TITLE
Processo de impressão

### ISSUE THREAD

**Issue by marcosandrade22** [pedrocasado/nfse-php#1]
Poderia dar uma ajuda de como se faz o processo de impressão da nota?

**Comment by pedrocasado** [comment]
Vê se você consegue pegar o PDF acessando o link com o código de verificação.

https://notacarioca.rio.gov.br/contribuinte/notaprint.aspx?ccm={CODIGO_DO_MUNICIPIO}&nf={NUMERO_DA_NF}&cod={COD_VERIFICACAO}
