### ISSUE TITLE
Instalação no PHP 7

### ISSUE THREAD

**Issue by gustavosfreitas** [pedrocasado/nfse-php#4]
Poderia me dar uma ajuda. Estou com erro na instalação.

Using version ^2.0 for pedrocasado/nfse-php
./composer.json has been updated
Running composer update pedrocasado/nfse-php
> php artisan clear-compiled
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pedrocasado/nfse-php[v2.0.0, ..., v2.0.2] require symfony/serializer 3.4.* -> satisfiable by symfony/serializer[v3.4.0, ..., v3.4.47].

**Comment by pedrocasado** [comment]
Corrigido na v2.0.3
